---
title: "P8133 Project"
author: "haokun yuan"
date: "11/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# may need to calculate # of people in each in arm

# one simulation
instance=function(size,true_fatal,ntrt){
  names(true_fatal)= c(1:ntrt)
  nsim=100
  week1 = sample(18,30*nsim,replace = TRUE) ### sample different regimen
  size = size-30 ### week 1 enroll 30
  week = true_fatal
  names(week)=c(1:18)#### label regimen num with true_fatal
  t = unclass(table(week1)) ### num patient assigned to each regimen
  for (i in names(t)){
    #print(i)
    week[i] = sum(rbinom(t[[i]],1,true_fatal[[as.numeric(i)]]))/(t[[i]]) ###  simulate death rate for each regimen
  }
  response = rbind(true_fatal,week)
  after1week(response,2,size)
}

after1week = function(response,nweek,size){
  nsim=100
  print(size)
  if (size>0){
   week1after = sample(18,10*nsim,replace = TRUE,prob = c(response[nweek-1,]))#need some modification here update start at week3
    names(week1after)=c(1:18)
    t = unclass(table(week1after))
    #print("..")
    #print(t)
    mat = matrix(,nrow = nsim,ncol = 18)
    for (j in 1:nsim){
      for (i in names(t)){
        #print(i)
        mat[j,as.numeric(i)] = sum(rbinom(t[[i]],1,true_fatal[[as.numeric(i)]]))/(t[[i]]) #!!!!!!
      }# need to used rstan to get the pi
    } 
    t1 = unclass(table(t(apply(mat, 1, order)[ 1, ])))
    for (i in names(t1)){
      week[i]=t1[[i]]/nsim
    }
    response = rbind(response,week)
    nweek=nweek+1
    size = size-10
    print(size)
    return(after1week(response,nweek,size))
  }else{
      return(response)
    }
}  

true_fatal=c(rep(0.15,6),rep(0.4,12))
ntrt=18
nweek=2
size=250
instance(250,true_fatal,18)
after1week(response,2,250)
```

```{r}
sim_data=
stan_data=list(N=18, X=model.matrix(~))
```

